### PR TITLE
Update notice color and text shadow

### PR DESCRIPTION
**Pull request by luise**
The notice box now looks like this:

screenshot 2017-07-30 12 02 02

### CODE REVIEW

**Comment by kayousterhout** [comment]
It looks weird to me that this is the same color as the table of contents -- can this be a different color, like it was before?  Maybe one of the accent colors?

**Comment by luise** [comment]
Better? 
screenshot 2017-07-31 10 21 27

**Comment by kayousterhout** [comment]
That looks great!!

**Comment by kklin** [comment]
Just let me know when I should merge @kayousterhout

**Comment by luise** [comment]
@kklin , I didn't push yet -- will ping you in a few.

**Comment by luise** [comment]
@kklin updated

**Comment by kayousterhout** [comment]
This looks great thanks @luise!!

**Pull request merged**
